using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GuessGameApp
{
    class Program
    {
        public static int generatedNumber = 0;
        public static Random rand = new Random();
        public static bool isGameover = false;
        static void Main(string[] args)
        {
            while (true)
            {
                Console.WriteLine("Game Generated By Advait, copyright @ 2021");
                generatedNumber = rand.Next(1, 101);

                Console.WriteLine(generatedNumber);
                int userNumber = 0;

                do
                {
                    Console.WriteLine("Enter a Number between 1 and 100");
                    userNumber = Convert.ToInt32(Console.ReadLine());
                    GuessNumber(userNumber);
                }
                while (!isGameover);

                Console.ReadLine();
            }
        }

        public static void GuessNumber(int userNumber)
        {
            int playAgain = 0;

            if (userNumber < generatedNumber)
                Console.WriteLine("Too low. Try Again.");
            else if (userNumber > generatedNumber)
                Console.WriteLine("Too High . Try Again");
            else
            {
                Console.WriteLine(" You Got it ! Press 1 to play again or 2 to quit");
                playAgain = Convert.ToInt32(Console.ReadLine());

                while (playAgain != 1 && playAgain != 2)
                {
                    Console.WriteLine("Plese select 1 to play again, or 2 to quit");
                    playAgain = Convert.ToInt32(Console.ReadLine());
                }
                if (playAgain.Equals(2))
                    isGameover = true;
                else
                {
                    generatedNumber = rand.Next(1, 101);
                    Console.WriteLine(generatedNumber);

                }
            }
            {
                Console.WriteLine("Thank You! for using my application, pls contact me advait.kunte@aurionpro.com");
            }

        }
    }
}
